### ISSUE TITLE
Lock-exchange is not working when ilmn is False

### ISSUE THREAD

**Issue by fschuch** [xcompact3d/Incompact3d#55]
The lock-exchange flow configuration is not working when `ilmn` is False.

We get this error:
```
 Xcompact3d is run with the default file -->input.i3d                                                                       
 ===========================================================
 ======================Xcompact3D===========================
 ===Copyright (c) 2018 Eric Lamballais and Sylvain Laizet===
 ===Modified by Felipe Schuch and Ricardo Frantz============
 ===Modified by Paul Bartholomew, Georgios Deskos and=======
 ===Sylvain Laizet -- 2018- ================================
 ===========================================================
 Git version        : v3.0-397-gff531df
 ===========================================================
 Simulating lock-exchange
 ===========================================================
 Reynolds number Re     :          2236.000
 xnu                    :        0.00044723
 ===========================================================
 p_row, p_col           :         0       0
 ===========================================================
 Time step dt           :        0.00480000
 Temporal scheme        :    Adams-bashforth 2
 ===========================================================
 ifirst                 :                 1
 ilast                  :            100000
 ===========================================================
 Lx                     :       18.00000000
 Ly                     :        2.00000000
 Lz                     :        2.00000000
 nx                     :               181
 ny                     :                29
 nz                     :                27
 ===========================================================
 istret                 :                 0
 beta                   :        0.25906515
 ===========================================================
 nu0nu                  :        4.00000000
 cnu                    :        0.44000000
 ===========================================================
 Scalar                 :               off
 numscalar              :                 0
 ===========================================================
 spinup_time            :                 0
 wrotation              :        0.00000000
 ===========================================================
 Immersed boundary      :               off
 ===========================================================
 Boundary condition velocity field: 
 nclx1, nclxn           :               1,1
 ncly1, nclyn           :               2,1
 nclz1, nclzn           :               1,1
 ===========================================================
 Numerical precision: Double
 ===========================================================
 High and low speed : u1=  2.00 and u2=  1.00
 Gravity vector     : (gx, gy, gz)=(     0.00000000,    -1.00000000,     0.00000000)
  
 Initial front location:    1.0000000000000000     
 ===========================================================
 In auto-tuning mode......
 factors:            1
 processor grid           1  by            1  time=   3.2067000000068901E-003
 the best processor grid is probably            1  by            1
 Initializing variables...
 Using the hyperviscous operator with (nu_0/nu,c_nu) = (   4.0000000000000000      ,  0.44000000000000000      )
 Using the hyperviscous operator with (nu_0/nu,c_nu) = (   4.0000000000000000      ,  0.44000000000000000      )
 Using the hyperviscous operator with (nu_0/nu,c_nu) = (   4.0000000000000000      ,  0.44000000000000000      )
 ===========================================================
 Visu module requires   0.267573029     GB
 ===========================================================
 ===========================================================
 Diffusion number
 cfl_diff_x             :           0.00021467
 cfl_diff_y             :           0.00042075
 cfl_diff_z             :           0.00036279
 cfl_diff_sum           :           0.00099821
 ===========================================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f07f6c802ed in ???
#1  0x7f07f6c7f503 in ???
#2  0x7f07f62fd03f in ???
#3  0x7f07f644cbe2 in ???
#4  0x55a8f26b4b5c in __lockexch_MOD_set_fluid_properties_lockexch
        at src/BC-Lock-exchange.f90:754
#5  0x55a8f26b4b5c in __lockexch_MOD_init_lockexch
        at src/BC-Lock-exchange.f90:175
#6  0x55a8f277a554 in __case_MOD_init
        at src/case.f90:93
#7  0x55a8f27e81fe in init_xcompact3d_
        at src/xcompact3d.f90:237
#8  0x55a8f2402918 in xcompact3d
        at src/xcompact3d.f90:50
#9  0x55a8f2402918 in main
        at src/xcompact3d.f90:35
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node DESKTOP-RD7V3T4 exited on signal 11 (Segmentation fault).
```

### Reproduce the error

Take the [Lock-exchange/input.i3d ](https://github.com/xcompact3d/Incompact3d/blob/f9e081b3b59f6c110fcbacbed74dab6ab02431a1/examples/Lock-exchange/input.i3d) and change:

```diff
- ilmn = .TRUE.         ! Enable low Mach number
+ ilmn = .FALSE.         ! Enable low Mach number
```

Then run the simulation.

### Proposed solution

I see two options:

1. Allocate `mu1` anyway. Right now the code at [src/variables.f90](https://github.com/xcompact3d/Incompact3d/blob/f9e081b3b59f6c110fcbacbed74dab6ab02431a1/src/variables.f90#L166) is:

    ```fortran
    if (ilmn) then
        call alloc_x(mu1)
        mu1(:,:,:) = one
    endif
    ```

2. Or protect references to `mu1` at [src/BC-Lock-exchange.f90](https://github.com/xcompact3d/Incompact3d/blob/f9e081b3b59f6c110fcbacbed74dab6ab02431a1/src/BC-Lock-exchange.f90) with `if (ilmn) then`.

**Comment by pbartholomew08** [comment]
I think option 2 sounds best.
